config/routes.rb
Rails.application.routes.draw do
  resources :appointment_dates

  ## Devise
  devise_for :users

  ## Letter_opener
  # mount LetterOpenerWeb::Engine, at: '/letter_opener'

  ## >>>>>> Root >>>>>>>>
  root to: 'home#index'

  ## Resources
  resources :users
  resources :medicines
  resources :diseases do
    collection do
      get 'search'
    end
  end
  resources :users
  resources :couriers
  resources :categories
  resources :patient_appointments do
    collection do
      get 'all_doctor'
      get 'history'
    end
  end
  resources :appointment_dates

  # require 'sidekiq-ent/web'
  # mount Sidekiq::Web => '/sidekiq'
end

app/models/medicine.rb
class Medicine < ApplicationRecord
  include Searchqueries
  belongs_to :user

  # Association
  has_many :categories
  has_many :medicine_diseases
  has_many :diseases, through: :medicine_diseases

  validates_presence_of :description, :quantity, :price, :manfucturing_date, :expiry_date
end

app/controllers/medicines_controller.rb
class MedicinesController < ApplicationController
  before_action :authenticate_user!
  before_action :ensure_current_user
  respond_to :html, :json, :js
  before_action :set_medicine, only: %i[show edit update destroy]

  def index
    @pagy, @medicines = pagy(Medicine.all)
    @search_medicine = Medicine.searched(params[:search]) if params[:search].present?
    respond_to do |format|
      format.html
      format.js
      format.pdf do
        render pdf: 'Medicines', template: 'medicines/medicine_records', formats: [:html]
      end
    end
  end

  def new
    @medicine = Medicine.new
    authorize @medicine
  end

  def create
    @medicine = current_user.medicines.new(medicine_params)
    respond_to do |format|
      if @medicine.save
        format.html { redirect_to medicines_url, notice: 'Medicine was successfully created.' }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def edit
    authorize @medicine
    @medicine = Medicine.find(params[:id])
  end

  def update
    @medicine = Medicine.find(params[:id])
    respond_to do |format|
      if @medicine.update(medicine_params)
        format.html { redirect_to medicines_url, notice: 'Medicine was successfully updated.' }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  def show
    @medicine = Medicine.find(params[:id])
    respond_to do |format|
      format.html
      format.pdf do
        render pdf: 'file_name', template: 'medicines/medicine', formats: [:html]
      end
    end
  end

  def destroy
    @medicine = Medicine.find(params[:id])

    # Admin authorization
    authorize @medicine

    @medicine.destroy
    respond_to do |format|
      format.html { redirect_to medicines_url, notice: 'Selected Medicine was successfully destroyed.' }
    end
  end

  private

  def set_medicine
    @medicine = Medicine.find(params[:id])
  end

  def medicine_params
    params.require(:medicine).permit(:name, :description, :quantity, :price, :manfucturing_date, :expiry_date)
  end

  def current_medicine
    @medicine = Medicine.find(params[:id])
  end
end

app/helpers/medicines_helper.rb
module MedicinesHelper
end

app/views/medicines/_results.html.erb
         <!--Searched Medicine Table--> 

<% if @search_medicine.present? %>
  <ul>
    <% @search_medicine&.each_with_index do |medicine, index| %>
    <li>
      <%= link_to medicine.name, medicine_url(medicine)%>
    </li>
<% end %>
  </ul>
<% end %>

app/views/medicines/_search.html.erb
  <!--Search field-->
<div class="row float-right">
  <div class="col-md-12 bg-light text-right id=search-form">
    <p>Search:</p>
    <%= form_tag(medicines_path, method: "get", remote: true) do %>
      <%= text_field_tag :search, params[:search], placeholder: "Enter Medicine name", autocomplete: "off" , class: "form-control" %>
    <% end %> 

    <div id="index">
      <%= render 'medicines/results' %>
    </div>   
  </div>
</div>

app/views/medicines/edit.html.erb
   <!-- Update Medicine Form-->
<div class="form-group">
  <div class="container-fluid">
    <div class="row justify-content-center">
      <div class="col-4">
        <div class="card">
          <div class="card-body">
            <h2> Update Medicine Details </h2>
            <%= simple_form_for @medicine do |f| %>
              <%= f.error_notification %>
              <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
              <div class="mb-3">
                <%= f.label :name, { class: "form-label"} %>
                <%= f.text_field :name, { class: "form-control", placeholder: "Medicine Name" } %>
              </div>
             
              <div class="mb-3">
                <%= f.label :description, { class: "form-label"} %>
                <%= f.text_field :description, { class: "form-control", placeholder: "Medicine Description" } %>
              </div>
             
              <div class="mb-3">
                <%= f.label :quantity, { class: "form-label"} %>
                <%= f.text_field :quantity, { class: "form-control", placeholder: "Medicine Quantity" } %>
              </div>
             
              <div class="mb-3">
                <%= f.label :price, { class: "form-label"} %>
                <%= f.text_field :price, { class: "form-control", placeholder: "Medicine Price" } %>
              </div>
             
              <div class="mb-3">
                <div class="field"><%= f.input :manfucturing_date %></div>
              </div>
             
              <div class="mb-3">
                <div class="field"><%= f.input :expiry_date %></div>
              </div>
             
              <div class="mb-3">
                <div><%= f.submit "Save", class: "btn btn-primary" %></div>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/medicines/index.html.erb
  <!-- All Medicines Record-->

<div class="container">
  <h2>Medicines</h2>
  <div class="row float-right">
    <div class="col-md-12 bg-light text-right">
      <%= link_to "Download All Record",medicines_path(@medicines,params: params.to_unsafe_h,format: :pdf), class: "btn btn-secondary" %>
    </div>
  </div>    <br /><br />
  <%= render 'medicines/search' %>
 
 <br /><br /><br /><br /><br /><br /><br /><br />

  <div id="disease-table">
    <div class="container fluid">
      <div class="row">
        <table class="table table-striped table-bordered">
          <thead>
            <tr>
              <th>Sr. #</th>
              <th>Name</th>
              <th>Description</th>
              <th>Quantity</th>
              <th>Price</th>
              <th>Manufacturing Date</th>
              <th>Medicine Expiry Date</th>
              <% if current_user.admin? %>
                <th colspan="4">Actions</th>
              <% end %>
            </tr>
          </thead>

          <tbody>
             <%- @medicines.each_with_index do |medicine, index| %>
              <tr class="table_test">
                <td><%= index + 1 %></td>
                <td><%= medicine.name %></td>
                <td><%= medicine.description %></td>
                <td><%= medicine.quantity %></td>
                <td><%= medicine.price %></td>
                <td><%= medicine.manfucturing_date %></td>
                <td><%= medicine.expiry_date %></td>
                <% if current_user.admin? %>
                  <td><%= link_to "Edit", edit_medicine_url(medicine), class: "btn btn-warning float-right"%></td>
                  <td><%= link_to "show", medicine_url(medicine), class: "btn btn-success float-right"%></td>
                  <td><%= button_to 'Delete', medicine_path(medicine), class: "btn btn-danger float-right", method: 'delete' %></td>
                  <td><%= link_to 'Download', medicine_path(medicine, format: :pdf), class: "btn btn-secondary float-right" %></td>
                <% end %>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
              <!--Pagination-->
      <%== pagy_bootstrap_nav(@pagy) %>

      <% if current_user.admin? %>
        <%= link_to "Add New Medicine", new_medicine_path, class: "btn btn-primary" %>
      <% end %>  
      <%= link_to 'Back', url_for(:back), class: "btn btn-primary" %>
    </div>
  </div>
</div> 


<script>
$(".table_test").hover(function(){
  $(this).css("background-color", "pink")
},
function(){
  $(this).css("background-color", "white")
});
</script>      

app/views/medicines/index.js.erb
$("#index").html("<%= escape_javascript(render :partial => 'results') %>");

app/views/medicines/medicine.html.erb
PDF generation date 
<%= Date.today %>

<h3>Medicine Details</h3>
<p>Medicine ID:  <%= @medicine.id %></p>
<p>Medicine Name:  <%= @medicine.name %></p>
<p>Description:  <%= @medicine.description %></p>
<p>Quantity:  <%= @medicine.quantity %></p>
<p>Price:  <%= @medicine.price %></p>
<p>Manufacturing Date:  <%= @medicine.manfucturing_date %></p>
<p>Expiry Date:  <%= @medicine.expiry_date %></p>

app/views/medicines/medicine_records.html.erb
  <!-- All Medicines Record-->

<div class="container">
  <h2>Medicines</h2>

  <div id="disease-table">
    <div class="container fluid">
      <div class="row">
        <table class="table table-striped table-bordered">
          <thead>
            <tr>
              <th>Sr. #</th>
              <th>Name</th>
              <th>Description</th>
              <th>Quantity</th>
              <th>Price</th>
              <th>Manufacturing Date</th>
              <th>Medicine Expiry Date</th>
          </thead>

          <tbody>
             <%- @medicines.each_with_index do |medicine, index| %>
              <tr>
                <td><%= index + 1 %></td>
                <td><%= medicine.name %></td>
                <td><%= medicine.description %></td>
                <td><%= medicine.quantity %></td>
                <td><%= medicine.price %></td>
                <td><%= medicine.manfucturing_date %></td>
                <td><%= medicine.expiry_date %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div> 


      

app/views/medicines/new.html.erb
   <!-- Medicine Form-->
<div class="form-group">
  <div class="container-fluid">
    <div class="row justify-content-center">
      <div class="col-4">
        <div class="card">
          <div class="card-body">
            <h2> Medicine Details </h2>
            
            <%= simple_form_for @medicine do |f| %>
              <%= f.error_notification %>
              <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
                
              <div class="mb-3">
                <%= f.label :name, { class: "form-label"} %>
                <%= f.text_field :name, { class: "form-control", placeholder: "Medicine Name" } %>
              </div>
                
              <div class="mb-3">
                <%= f.label :description, { class: "form-label"} %>
                <%= f.text_field :description, { class: "form-control", placeholder: "Medicine Description" } %>
              </div>
              
              <div class="mb-3">
                <%= f.label :quantity, { class: "form-label"} %>
                <%= f.text_field :quantity, { class: "form-control", placeholder: "Medicine Quantity" } %>
              </div>
                
              <div class="mb-3">
                <%= f.label :price, { class: "form-label"} %>
                <%= f.text_field :price, { class: "form-control", placeholder: "Medicine Price" } %>
              </div>
              
              <div class="mb-3">
                <div class="field"><%= f.input :manfucturing_date %></div>
              </div>
                
              <div class="mb-3">
                <div class="field"><%= f.input :expiry_date %></div>
              </div>
               
              <div class="mb-3">
                <div><%= f.submit "Save", class: "btn btn-primary" %></div>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/medicines/show.html.erb
  <!-- Medicine Table -->
<div class="container fluid">
  <h1>Medicine</h1>
  <div class="row">
    <table class="table table-striped table-bordered">
      <thead>
        <tr>
          <th>Name</th>
          <th>Description</th>
          <th>Quantity</th>
          <th>Price</th>
          <th>Manufacturing Date</th>
          <th>Medicine Expiry Date</th>
          <th colspan="3">Actions</th>
        </tr>
      </thead>
    <tbody>
      <tr>
        <td><%= @medicine.name %></td>
        <td><%= @medicine.description %></td>
        <td><%= @medicine.quantity %></td>
        <td><%= @medicine.price %></td>
        <td><%= @medicine.manfucturing_date %></td>
        <td><%= @medicine.expiry_date %></td>
        <td><%= link_to "Edit", edit_medicine_url, class: "btn btn-warning float-right"%></td>
        <td><%= button_to 'Delete', medicine_path, class: "btn btn-danger float-right", method: 'delete' %></td>
        <td><%= link_to 'Download', medicine_path(format: :pdf), class: "btn btn-secondary float-right" %></td>
      </tr>
    </tbody>
    </table>
  </div>
    <%= link_to "Add New Medicine", new_medicine_path, class: "btn btn-primary" %>
</div>