config/routes.rb
Rails.application.routes.draw do
  resources :appointment_dates

  ## Devise
  devise_for :users

  ## Letter_opener
  # mount LetterOpenerWeb::Engine, at: '/letter_opener'

  ## >>>>>> Root >>>>>>>>
  root to: 'home#index'

  ## Resources
  resources :users
  resources :medicines
  resources :diseases do
    collection do
      get 'search'
    end
  end
  resources :users
  resources :couriers
  resources :categories
  resources :patient_appointments do
    collection do
      get 'all_doctor'
      get 'history'
    end
  end
  resources :appointment_dates

  # require 'sidekiq-ent/web'
  # mount Sidekiq::Web => '/sidekiq'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/appointment_date.rb
class AppointmentDate < ApplicationRecord
  belongs_to :user
end

app/models/category.rb
class Category < ApplicationRecord
  include Searchqueries
  belongs_to :user
  belongs_to :disease
  belongs_to :medicine
end

app/models/courier.rb
class Courier < ApplicationRecord
  include Searchqueries
  belongs_to :user
  validates_presence_of :address, :code, :contact_no

  scope :searched, ->(name) { where('name ILIKE ?', "%#{name}%") }
end

app/models/disease.rb
class Disease < ApplicationRecord
  include Searchqueries
  enum :status, %i[active inactive]

  validates_presence_of :code, :status

  # Association
  belongs_to :user
  has_many :categories
  has_many :medicine_diseases
  has_many :medicines, through: :medicine_diseases, dependent: :destroy

  has_many :user_diseases
  has_many :users, through: :user_diseases, dependent: :destroy

  # class method
  # def self.get_all_diseases
  #  disease = self.all
  # end

  # instance method
  def get_all_diseases
    disease = all
  end
end

app/models/medicine.rb
class Medicine < ApplicationRecord
  include Searchqueries
  belongs_to :user

  # Association
  has_many :categories
  has_many :medicine_diseases
  has_many :diseases, through: :medicine_diseases

  validates_presence_of :description, :quantity, :price, :manfucturing_date, :expiry_date
end

app/models/medicine_disease.rb
class MedicineDisease < ApplicationRecord
  # attr_accessible :medicine_id, :disease_id
  belongs_to :medicine
  belongs_to :disease
end

app/models/notification.rb
class Notification < ApplicationRecord
  belongs_to :notifiable , :polymorphic => true
end

app/models/patient_appointment.rb
class PatientAppointment < ApplicationRecord
  belongs_to :user
  has_many :notifications, :as => :notifiable, dependent: :destroy 
  scope :not_yet_done, -> { where('date > ?', Time.now) } 
  scope :previous_appointment, -> { where('date < ?', Time.now) }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  # after_create :send_admin_mail

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable, :timeoutable, :trackable

  # User roles
  enum role: %i[admin patient doctor]
  after_initialize :set_default_role, if: :new_record?

  def set_default_role
    self.role ||= :admin
  end

  PASSWORD_FORMAT = /\A
  (?=.{8,})          # Must contain 8 or more characters
  (?=.*\d)           # Must contain a digit
  (?=.*[a-z])        # Must contain a lower case character
  (?=.*[A-Z])        # Must contain an upper case character
  (?=.*[[:^alnum:]]) # Must contain a symbol /x

  # Associations
  has_many :diseases
  has_many :medicines
  has_many :couriers
  has_many :categories
  has_many :patient_appointments
  has_many :appointment_dates
  has_many :user_diseases
  has_many :diseases, through: :user_diseases, dependent: :destroy
  has_many :notifications, :as => :notifiable
  has_one_attached :avatar

  validates_presence_of :name, :lname
  validates :password, format: { with: PASSWORD_FORMAT }, confirmation: true, on: :create, on: :update

  scope :all_except, ->(user) { where.not(id: user) }
end

app/models/user_disease.rb
class UserDisease < ApplicationRecord
  belongs_to :user
  belongs_to :disease
end

app/controllers/appointment_dates_controller.rb
class AppointmentDatesController < ApplicationController
  before_action :authenticate_user!
  before_action :ensure_current_user
  before_action :set_appointment_date, only: %i[show edit update destroy]

  def index
    @appointment_dates = AppointmentDate.all if current_user.admin?
    return unless current_user.doctor?

    @appointment_dates = current_user.appointment_dates.all
  end

  def show
    @appointment_date = AppointmentDate.find(params[:id])
  end

  def new
    @appointment_date = AppointmentDate.new
    authorize @appointment_date
  end

  def edit
    @appointment_date = AppointmentDate.find(params[:id])
    authorize @appointment_date
  end

  def create
    @appointment_date = AppointmentDate.create(appointment_date_params)
    redirect_to appointment_dates_url
  end

  def update
    @appointment_date = AppointmentDate.find(params[:id])
    respond_to do |format|
      dates
      if @appointment_date.update(appointment_date_params)
        format.html do
          redirect_to appointment_dates_url, notice: 'Doctor availability date was successfully updated.'
        end
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @appointment_date = AppointmentDate.find(params[:id])
    authorize @appointment_date
    @appointment_date.destroy
    respond_to do |format|
      format.html { redirect_to appointment_dates_url, notice: 'Doctor availability date was successfully destroyed.' }
    end
  end

  private

  def set_appointment_date
    @appointment_date = AppointmentDate.find(params[:id])
  end

  def appointment_date_params
    params.require(:appointment_date).permit(:start_time, :end_time, :user_id)
  end
end

app/controllers/couriers_controller.rb
class CouriersController < ApplicationController
  before_action :authenticate_user!
  before_action :ensure_current_user

  def index
    @pagy, @couriers = pagy(Courier.all)
    @courier = current_user.couriers.new

    return unless params[:search].present?
    @search_courier = Courier.searched(params[:search])
    respond_to do |format|
      format.js
    end
  end

  def new
    respond_to do |format|
      format.html
      format.js
    end
  end

  def create
    @courier = current_user.couriers.new(courier_params)
    respond_to do |format|
      if @courier.save
        format.html { redirect_to couriers_url, notice: 'Courier was successfully created.' }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def edit
    @courier = Courier.find(params[:id])
  end

  def update
    respond_to do |format|
      if @courier.update(courier_params)
        format.html { redirect_to couriers_url, notice: 'Courier was successfully updated.' }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  def show
    @courier = Courier.find(params[:id])
  end

  def destroy
    @courier = Courier.find(params[:id])
    @courier.destroy
    respond_to do |format|
      format.html { redirect_to couriers_url, notice: 'Selected courier was successfully destroyed.' }
    end
  end

  private

  def set_courier
    @courier = Courier.find(params[:id])
  end

  def courier_params
    params.require(:courier).permit(:name, :address, :code, :contact_no)
  end

  def current_courier
    @courier = Courier.find(params[:id])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!
  before_action :ensure_current_user

  def index; end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def index
    @users = User.all_except(current_user)
  end  

  def destroy
    @user = User.find(params[:id])
    respond_to do |format|
      @user.destroy
      format.html { redirect_to users_url, notice: 'Selected User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  include Pagy::Frontend
end

app/helpers/appointment_dates_helper.rb
module AppointmentDatesHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/couriers_helper.rb
module CouriersHelper
end

app/helpers/diseases_helper.rb
module DiseasesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/medicines_helper.rb
module MedicinesHelper
end

app/helpers/users_helper.rb
module UsersHelper
  # def user_avatar user
  #   if user.image.present?
  #     image_tag user.avatar
  #   end
  # end
end

app/views/appointment_dates/_appointment_date.html.erb
<div id="<%= dom_id appointment_date %>">
  <p>
    <strong>Doctor:</strong>
    <%= appointment_date.doctor_id %>
  </p>

  <p>
    <strong>Start time:</strong>
    <%= appointment_date.start_time %>
  </p>

  <p>
    <strong>End time:</strong>
    <%= appointment_date.end_time %>
  </p>

</div>

app/views/appointment_dates/_form.html.erb
<div class="form-group">
  <div class="container-fluid text-center">
    <div class="row justify-content-center">
      <div class="col-4">
      <h2>Doctor Appointment Dates</h2>
        <div class="card">
          <div class="card-body">
            <%= form_for AppointmentDate.new do |f| %>
             
                <div class="mt-3">
                  <%= f.datetime_select :start_time %>
                </div>
                <%= f.hidden_field :user_id , value: current_user.id %>
                <div class="mt-3 mb-3">
                  <%= f.datetime_select :end_time %>
                </div>  
              </div>

              <div class="form-actions">
                <%= f.button :submit, class:"btn btn-primary" %>
              </div>

              <div class="mt-3">
                <%= link_to "Back", appointment_dates_path, class:"btn btn-primary" %>
              </div>
            <% end %>
          </div>
        </div>    
      </div>
    </div>
  </div>
</div>        

<script>
  
  $(document).ready(function() {
    $('.value-selector').select2();
  });

</script>

app/views/appointment_dates/edit.html.erb
<%= render "form", appointment_date: @appointment_date %>

app/views/appointment_dates/index.html.erb
<div class="container">
  <h2>Doctors Avalibility Dates</h2>
  <div class="container fluid">
    <div class="row">
      <table class="table table-striped table-bordered">
        <thead> 
          <tr>
            <th>Sr. #</th>
            <th>Date</th>
            <th>Availability</th>
            <% if current_user.doctor? %>
              <th colspan="3">Actions</th>
            <% end %>
            </tr>
          </thead>
          <tbody>
            <% @appointment_dates.each_with_index do |appointment_date, index| %>
              <tr class="table_test">
                <td><%= index + 1 %></td>
                <td><%= appointment_date.start_time.strftime("%d/%m/%Y") %></td>
                <td>
                  <%= appointment_date.start_time.strftime("%I:%M %p") %>
                  <strong> To </strong>
                  <%= appointment_date.end_time.strftime("%I:%M %p") %>
                </td>
                <% if current_user.doctor? %>
                  <td><%= link_to "Edit", edit_appointment_date_url(appointment_date), class: "btn btn-warning float-right"%></td>
                  <td><%= link_to "Show", appointment_date_url(appointment_date), class: "btn btn-success float-right"%></td>
                  <td><%= button_to 'Delete', appointment_date_path(appointment_date), class: "btn btn-danger float-right", method: 'delete' %></td>
                <% end %> 
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
      <%= link_to "New appointment date", new_appointment_date_path, class: "btn btn-primary" %>
      <%= link_to 'Back', url_for(:back), class: "btn btn-primary" %>
    </div>
  </div>
</div>

<script>
$(".table_test").hover(function(){
  $(this).css("background-color", "pink")
},
function(){
  $(this).css("background-color", "white")
});
</script>

app/views/appointment_dates/new.html.erb
<%= render "form", appointment_date: @appointment_date %>

app/views/appointment_dates/show.html.erb
<div class="form-group">
  <div class="container-fluid text-center">
    <div class="row justify-content-center">
      <div class="col-4">
      <h2>Doctor Appointment Date</h2>
        <div class="card">
          <div class="card-body">
            <strong> Doctor Name:</strong>
            <%= @appointment_date.doctor.name %><br>
            <strong> Date:</strong>
            <%= @appointment_date.start_time.strftime("%d/%m/%Y") %><br>
            <strong> Availability:</strong>
            <%= @appointment_date.start_time.strftime("%I:%M %p") %>
            <strong> To </strong>
            <%= @appointment_date.end_time.strftime("%I:%M %p") %>
            <div class="btn-group">
              <%= link_to "Edit", edit_appointment_date_url, class: "btn btn-warning editdate"%>
              <%= button_to 'Delete', appointment_date_path, class: "btn btn-danger", method: 'delete' %>
            </div>
          </div>
        </div>
        <div class="mt-3">
          <%= link_to 'Back', url_for(:back), class: "btn btn-primary" %>
        </div>
      </div>
    </div>
  </div>
</div>