config/routes.rb
Rails.application.routes.draw do
  resources :appointment_dates

  ## Devise
  devise_for :users

  ## Letter_opener
  # mount LetterOpenerWeb::Engine, at: '/letter_opener'

  ## >>>>>> Root >>>>>>>>
  root to: 'home#index'

  ## Resources
  resources :users
  resources :medicines
  resources :diseases do
    collection do
      get 'search'
    end
  end
  resources :users
  resources :couriers
  resources :categories
  resources :patient_appointments do
    collection do
      get 'all_doctor'
      get 'history'
    end
  end
  resources :appointment_dates

  # require 'sidekiq-ent/web'
  # mount Sidekiq::Web => '/sidekiq'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/appointment_date.rb
class AppointmentDate < ApplicationRecord
  belongs_to :user
end

app/models/category.rb
class Category < ApplicationRecord
  include Searchqueries
  belongs_to :user
  belongs_to :disease
  belongs_to :medicine
end

app/models/courier.rb
class Courier < ApplicationRecord
  include Searchqueries
  belongs_to :user
  validates_presence_of :address, :code, :contact_no

  scope :searched, ->(name) { where('name ILIKE ?', "%#{name}%") }
end

app/models/disease.rb
class Disease < ApplicationRecord
  include Searchqueries
  enum :status, %i[active inactive]

  validates_presence_of :code, :status

  # Association
  belongs_to :user
  has_many :categories
  has_many :medicine_diseases
  has_many :medicines, through: :medicine_diseases, dependent: :destroy

  has_many :user_diseases
  has_many :users, through: :user_diseases, dependent: :destroy

  # class method
  # def self.get_all_diseases
  #  disease = self.all
  # end

  # instance method
  def get_all_diseases
    disease = all
  end
end

app/models/medicine.rb
class Medicine < ApplicationRecord
  include Searchqueries
  belongs_to :user

  # Association
  has_many :categories
  has_many :medicine_diseases
  has_many :diseases, through: :medicine_diseases

  validates_presence_of :description, :quantity, :price, :manfucturing_date, :expiry_date
end

app/models/medicine_disease.rb
class MedicineDisease < ApplicationRecord
  # attr_accessible :medicine_id, :disease_id
  belongs_to :medicine
  belongs_to :disease
end

app/models/notification.rb
class Notification < ApplicationRecord
  belongs_to :notifiable , :polymorphic => true
end

app/models/patient_appointment.rb
class PatientAppointment < ApplicationRecord
  belongs_to :user
  has_many :notifications, :as => :notifiable, dependent: :destroy 
  scope :not_yet_done, -> { where('date > ?', Time.now) } 
  scope :previous_appointment, -> { where('date < ?', Time.now) }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  # after_create :send_admin_mail

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable, :timeoutable, :trackable

  # User roles
  enum role: %i[admin patient doctor]
  after_initialize :set_default_role, if: :new_record?

  def set_default_role
    self.role ||= :admin
  end

  PASSWORD_FORMAT = /\A
  (?=.{8,})          # Must contain 8 or more characters
  (?=.*\d)           # Must contain a digit
  (?=.*[a-z])        # Must contain a lower case character
  (?=.*[A-Z])        # Must contain an upper case character
  (?=.*[[:^alnum:]]) # Must contain a symbol /x

  # Associations
  has_many :diseases
  has_many :medicines
  has_many :couriers
  has_many :categories
  has_many :patient_appointments
  has_many :appointment_dates
  has_many :user_diseases
  has_many :diseases, through: :user_diseases, dependent: :destroy
  has_many :notifications, :as => :notifiable
  has_one_attached :avatar

  validates_presence_of :name, :lname
  validates :password, format: { with: PASSWORD_FORMAT }, confirmation: true, on: :create, on: :update

  scope :all_except, ->(user) { where.not(id: user) }
end

app/models/user_disease.rb
class UserDisease < ApplicationRecord
  belongs_to :user
  belongs_to :disease
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!
  before_action :ensure_current_user

  def index; end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def index
    @users = User.all_except(current_user)
  end  

  def destroy
    @user = User.find(params[:id])
    respond_to do |format|
      @user.destroy
      format.html { redirect_to users_url, notice: 'Selected User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  include Pagy::Frontend
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/couriers_helper.rb
module CouriersHelper
end

app/helpers/diseases_helper.rb
module DiseasesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/medicines_helper.rb
module MedicinesHelper
end

app/helpers/users_helper.rb
module UsersHelper
  # def user_avatar user
  #   if user.image.present?
  #     image_tag user.avatar
  #   end
  # end
end

app/views/layouts/_nav.html.erb
<!-- Navbar -->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container">
    <a class="navbar-brand" href="#">RoofTopClinic</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
            <% if not user_signed_in? %>
              <li class="nav-item"><%= link_to "Login", user_session_path, class: "btn btn-dark" %></li>  
              <li class="nav-item"><%= link_to "Sign Up", new_user_registration_path, class: "btn btn-dark" %></li>    
            <% end %>
            <% if user_signed_in? %>
              <li class="nav-item"><%= link_to "Profile", root_path, class: "btn btn-dark" %></li>
              <% if current_user.admin? || current_user.doctor? %>
                <li class="nav-item"><%= link_to "Checkup Time", appointment_dates_path, class: "btn btn-dark" %></li>
              <% end %>  
              <li class="nav-item"><%= link_to "Appointment", patient_appointments_path, class: "btn btn-dark" %></li>
              <% if current_user.patient? %>
                <li class="nav-item"><%= link_to "Doctors", all_doctor_patient_appointments_path, class: "btn btn-dark" %></li>
              <% end %>  

              <% if current_user.admin? || current_user.doctor? %>
                <li class="nav-item"><%= link_to "Diseases", diseases_path, class: "btn btn-dark" %></li>
                <li class="nav-item"><%= link_to "Medicines", medicines_path, class: "btn btn-dark" %></li>
                <li class="nav-item"><%= link_to "Categories", categories_path, class: "btn btn-dark" %></li>
              <% end %>  
              <% if current_user.admin? %>
                <li class="nav-item"><%= link_to "Couriers", couriers_path, class: "btn btn-dark" %></li>
                <li class="nav-item"><%= link_to "Users", users_path, class: "btn btn-dark" %></li>
              <% end %>
              <% if current_user.doctor? %>
                 <ul class="navbar-nav" id="unread-notification">
                    <%= render 'layouts/notifications' %>
                  </ul>
              <% end %> 
              <li class="nav-item"><%= button_to "Logout", destroy_user_session_path, { method: :delete, class: "btn btn-danger" } %></li>
            <% end %>
          </ul>
        </div>
  </div>
</nav>

app/views/layouts/_notifications.html.erb
<li class="nav-item dropdown position-relative not__dropdown ">
  <a class="nav-link dropdown-toggle " href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
      <%= render 'layouts/test' %>
    </a>
    <ul class="dropdown-menu dropdown-menu-lg-end" aria-labelledby="navbarDropdown">
        <div id="notification_data">
          <%- @notifications.each_with_index do |notification, index| %>
            <li>
              <div class="index_text"> 
                <%= index+1 %> 
              </div> 
              <div class="notification_text"> 
                Appointment booked to you by   
                <%= User.find(notification.user_id).name %> <%= User.find(notification.user_id).lname %> 
              </div>             
            </li>  
          <% end %> 
        </div>
    </ul>
</li>

app/views/layouts/_test.html.erb
<span class="badge rounded-pill bg-danger">
  <%= @notifications.count %><i class="fa fa-bell"></i>
</span>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RTC</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= javascript_importmap_tags %>
    <%= javascript_include_tag "http://code.jquery.com/jquery-1.10.0.min.js" %>
    <%= javascript_include_tag "http://code.jquery.com/ui/1.10.3/jquery-ui.min.js" %>
 
    <script type="text/javascript" src="jquery.simple-calendar.js"></script>
    <link rel="stylesheet" type="text/css" href="simple-calendar.css" />

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
    
    <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
    <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>

    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>

    <!--Bootstrap icons cdn-->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.2/font/bootstrap-icons.css">

    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/rateYo/2.3.2/jquery.rateyo.min.css">
    
    <!-- Latest compiled and minified JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/rateYo/2.3.2/jquery.rateyo.min.js"></script>
     
    <style>
      .float-right {
      float: right;
      }
    </style>
  </head>

  <body>
    <%= render 'layouts/nav' %>
    <%= render 'layouts/shared/notices' %>
    <%= yield %>
  </body>
</html>

app/views/layouts/pdf.html.erb
<!doctype html>
<html>
  <head>
    <meta charset='utf-8' />
    <%= wicked_pdf_stylesheet_link_tag "pdf" -%>
    <%= wicked_pdf_javascript_include_tag "number_pages" %>
  </head>
  <body onload='number_pages'>
    <div id="header">
      <%= wicked_pdf_image_tag 'mysite.jpg' %>
    </div>
    <div id="content">
      <%= yield %>
    </div>
  </body>
</html>

app/views/layouts/shared/_notices.html.erb
        <!-- Notices -->
<div class="notices">
  <p class="notice", style="color: green"><%= notice %></p>
  <p class="alert", style="color: red"><%= alert %></p>
</div>